FROM ubuntu:16.04
RUN apt-get update && apt-get install -y apache2 && apt-get -y install php7.0 libapache2-mod-php7.0 && echo "ServerName localhost" >> /etc/apache2/httpd.conf && echo "ServerName localhost" >> /etc/apache2/apache2.conf && a2enmod rewrite && rm /etc/apache2/apache2.conf && apt-get clean
RUN apt-cache search php7.0 && apt-get -y install php7.0-mysql php7.0-curl php7.0-gd php7.0-intl php-pear php-imagick php7.0-imap php7.0-mcrypt php-memcache  php7.0-pspell php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xmlrpc php7.0-xsl php7.0-mbstring php-gettext
COPY apache2.conf /etc/apache2/apache2.conf
ENV APACHE_LOCK_DIR="/var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="www-data"
ENV APACHE_RUN_GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2"
LABEL Description="Site"
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["apachectl"]